name: Docker Build and Push

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write
  contents: read
  packages: write
  actions: read

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag name
        id: get-tag-name
        run: echo "tag-name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ghcr.io/hpcslab/cfp-summary-server:${{ steps.get-tag-name.outputs.tag-name }}
          push: true
